# Generated by Django 4.2.11 on 2024-04-30 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_formulario_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='idade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
